# Generated by Django 3.2.6 on 2022-02-21 05:26

import ckeditor.fields
import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_To_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=100)),
                ('brand', models.CharField(default='', max_length=100)),
                ('customer', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=1)),
                ('product_id', models.IntegerField(default=1)),
                ('product_Qty', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=100)),
                ('message', ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_phone', models.CharField(default='', max_length=20)),
                ('customer_password', models.CharField(default='', max_length=40)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(default='', max_length=230)),
                ('customer_address', models.CharField(default='', max_length=150)),
                ('customer_city', models.CharField(default='islamabad', max_length=150)),
                ('customer_zipCode', models.IntegerField(default=0)),
                ('customer_province', models.CharField(default='Punjab', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField(default=0)),
                ('Order_Items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None)),
                ('Payment_id', models.CharField(default='', max_length=200)),
                ('Total_Price', models.IntegerField(default=0)),
                ('OrderDate', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
                ('reviews', models.TextField(default='')),
                ('customer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_name', models.CharField(max_length=150)),
                ('shipper_email', models.EmailField(max_length=100)),
                ('shipper_phone_no', models.CharField(max_length=20)),
                ('shipper_image', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('shipper_address', models.CharField(max_length=200)),
                ('shipper_Regiter_Date', models.DateField(default=datetime.date.today)),
                ('shipper_verified', models.BooleanField(default=True)),
                ('shipper_detail', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=150)),
                ('offer_Finish_Time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategory_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_email', models.EmailField(max_length=100)),
                ('supplier_phone_no', models.CharField(max_length=15)),
                ('supplier_address', models.CharField(max_length=100)),
                ('supplier_Regiter_Date', models.DateField(default=datetime.date.today)),
                ('supplier_verified', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyForm',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('Ans_of_Q1', models.CharField(default='', max_length=100)),
                ('Ans_of_Q2', models.CharField(default='', max_length=100)),
                ('Ans_of_Q3', models.CharField(default='', max_length=100)),
                ('Ans_of_Q4', models.CharField(default='', max_length=100)),
                ('Ans_of_Q5', models.CharField(default='', max_length=100)),
                ('Ans_of_Q6', models.CharField(default='', max_length=100)),
                ('Ans_of_Q7', models.CharField(default='', max_length=100)),
                ('Ans_of_Q8', models.CharField(default='', max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypbackendapi.customer')),
            ],
            options={
                'verbose_name_plural': 'Survey Results',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=500)),
                ('product_price', models.FloatField()),
                ('product_brand', models.CharField(max_length=500)),
                ('product_color', models.CharField(max_length=50)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('product_companyName', models.CharField(max_length=500)),
                ('product_total_stock', models.IntegerField()),
                ('place_of_origin', models.CharField(default='Islamabad', max_length=200)),
                ('product_weight', models.FloatField(default=0.0)),
                ('product_specification', ckeditor.fields.RichTextField(blank=True)),
                ('product_description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fypbackendapi.category')),
                ('subCategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fypbackendapi.subcategory')),
                ('supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fypbackendapi.supplier')),
            ],
        ),
    ]
