export  const ActionTypes=
{
    SET_CATEGORIES: "SET_CATEGORIES",
    SET_SUB_CATEGORIES: "SET_SUB_CATEGORIES",
    SET_CUSTOMERS: "SET_CUSTOMERS",
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_RATING:"SET_RATING",
    SET_SHIPPER:"SET_SHIPPER",
    SET_LOGIN:"SET_LOGIN",
    REMOVE_LOGIN:"REMOVE_LOGIN",
    SET_ADD_To_CART:"SET_ADD_To_CART",
}
export default ActionTypes